services:
  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql-wallet
    ports:
      - "3306:3306"
    env_file:
      - path: .env.mysql
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  wallet-db-service:
    build:
      context: ./wallet-db-service
      dockerfile: Dockerfile
    container_name: wallet-db
    ports:
      - "3000:3000"
    env_file: 
     - path: ./wallet-db-service/.env
    environment:
      APP_ENV: docker
    depends_on:
      - mysql

  wallet-api-service:
    build:
      context: ./wallet-api-service
      dockerfile: Dockerfile
    container_name: wallet-api
    ports:
      - "4000:3000"
    environment:
      APP_ENV: docker
    env_file: 
      - path: ./wallet-api-service/.env
    depends_on:
      - wallet-db-service

  wallet-frontend:
    build:
      context: ./wallet-frontend
      args:
        API_URL: http://localhost:4000
    container_name: wallet-frontend
    ports:
      - "5173:80"
    depends_on:
      - wallet-api-service

volumes:
  mysql_data:
